#!/bin/bash

apt update && apt upgrade -y
apt install git -y
pip3 install -U pip
git clone https://github.com/RuwinSankapala/solid-adventure solid-adventure
cd solid-adventure
pip3 install -U -r requirements.txt
python3 -m bot
